name: 'Chainlist Json Combine'
description: 'combine chain json files'
inputs:
  read-path:
    description: 'chain directory path'
  write-path:
    description: 'combined output path'
runs:
  using: 'node16'
  main: 'index.js'
